services:
  lucky:
    build:
      context: .
      dockerfile: docker/development.dockerfile
    environment:
      DATABASE_URL: postgres://lucky:password@postgres:5432/crystal_todo_list_development
      DEV_HOST: "0.0.0.0"
    volumes:
      - .:/app
      - node_modules:/app/node_modules
      - shards_lib:/app/lib
      - app_bin:/app/bin
      - build_cache:/root/.cache
    depends_on:
      - postgres
    ports:
      - 3000:3000 # This is the Lucky Server port
      - 3001:3001 # This is the Lucky watcher reload port

    entrypoint: ["docker/dev_entrypoint.sh"]

  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: lucky
      POSTGRES_PASSWORD: password
      POSTGRES_DB: crystal_todo_list_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # Port not exposed to host for security - access via container network only

volumes:
  postgres_data:
  node_modules:
  shards_lib:
  app_bin:
  build_cache:
