name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  lint:
    name: Lint & Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.18.2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run linter
        run: bin/lint --check

  test:
    name: Tests
    runs-on: ubuntu-latest
    env:
      LUCKY_ENV: test
      DB_HOST: localhost
      DATABASE_URL: postgres://postgres:postgres@localhost:5432/crystal_todo_list_test

    services:
      postgres:
        image: postgres:14-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: crystal_todo_list_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1
        with:
          crystal: 1.18.2

      - name: Install Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.0

      - name: Cache Crystal dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/crystal
            lib
          key: ${{ runner.os }}-crystal-${{ hashFiles('**/shard.lock') }}
          restore-keys: |
            ${{ runner.os }}-crystal-

      - name: Cache Bun dependencies
        uses: actions/cache@v4
        with:
          path: ~/.bun/install/cache
          key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
          restore-keys: |
            ${{ runner.os }}-bun-

      - name: Install Crystal dependencies
        run: shards install

      - name: Install Bun dependencies
        run: bun install --frozen-lockfile

      - name: Build assets
        run: bun run build

      - name: Build lucky_tasks
        run: crystal build tasks.cr -o ./lucky_tasks

      - name: Setup database
        run: |
          ./lucky_tasks db.create
          ./lucky_tasks db.migrate

      - name: Run tests
        run: |
          # Run frontend tests
          bun run test
          # Run backend tests
          crystal spec
